# @see: https://cristianadam.eu/20191222/using-github-actions-with-c-plus-plus-and-cmake/
# @see: virtual-environments/Windows2019-Readme.md at master · actions/virtual-environments https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md
name: Build GCC

on: [push]

jobs:
  build:
    name: gccbuild
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run GCC
      run: gcc WallpaperChanger.c -o WallpaperChanger -mwindows
      shell: cmd
